# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'The Fool Laureate'
tagline:          'I too have an opnion on that...'
description:      'None of the words here are my own, but the arrangements are.'
url:              http://mikesturm.github.io
baseurl:          '/'
paginate:         5

author:
  name: 'Mike Sturm'
  email: 'mike.p.sturm@gmail.com'
  twitter: aperfectsturm
  disqus_shortname: mike_sturm
  google_analytics_id: UA-71215621-1
  google_analytics_url: mikesturm.github.io
  bio: 

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/lanyon
